M48
; DRILL file KiCad 9.99.0-4890-gde912bdc9a date 2026-01-24T23:46:00-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-24T23:46:00-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.99.0-4890-gde912bdc9a
; #@! TF.FileFunction,NonPlated,1,8,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X159.234Y-55.71
X160.25Y-60.79
X161.266Y-55.71
T2
X103.5Y-47.5
X161.5Y-96.5
M30
