name: Export 3D Model
on: [push, workflow_dispatch]

jobs:
  export:
    runs-on: ubuntu-latest
    container:
      image: kicad/kicad:nightly
      options: --user root
    
    steps:
      - uses: actions/checkout@v4

      - name: Install 3D Libraries
        run: |
          apt-get update
          apt-get install -y --no-install-recommends kicad-packages3d

      - name: Prepare Output Directory
        run: mkdir -p 3d_models

      - name: Export GLB (Visual Model)
        env:
          KICAD9_3DMODEL_DIR: /usr/share/kicad/3dmodels/
        run: >
          kicad-cli pcb export glb 
          --subst-models 
          --include-tracks 
          --include-zones 
          --include-pads 
          -o 3d_models/RPi-HwAB.glb 
          pcb/RPi-HwAB-1.kicad_pcb

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GLB-File
          path: 3d_models